#!/bin/bash
#SBATCH -J 1-scaling		# Job name
#SBATCH -o 1-scaling-%j.out   # Name of stdout output file (%j expands to jobId)
#SBATCH -e 1-scaling-%j.err   # Name of error output file
#SBATCH -p normal		# Queue name
#SBATCH -N 2                  # Total number of cores requested (64 cores/node, 4 threads/core)
#SBATCH -n 64                 # Total number of mpi tasks requested
#SBATCH -t 2:00:00           # Run time (hh:mm:ss)
#SBATCH --mail-user=nelsonmorrow@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH -A relplasmas


module load launcher
RAD=250e-9
nicell=100

EXE=psc_test_windowLL
WORKDIR=$SCRATCH/build/src
mkdir $WORKDIR/data
mkdir -p "$HOME/PSC/Scripts/nicell_$nicell/"

export LAUNCHER_WORKDIR=$HOME/PSC/Scripts
export LAUNCHER_JOB_FILE=scaling
outfile=$HOME/PSC/Scripts/nicell_$nicell/2_node_scaling

echo "name,avg,min,max,total,timestep,numcores,nicell" > $outfile
{ export IBRUN_TASKS_PER_NODE=64 && let NUM_CORES=$IBRUN_TASKS_PER_NODE*$SLURM_NNODES && ibrun $WORKDIR/$EXE --nicell $nicell --outdir $WORKDIR/data | grep "time entire step" | sed "s/time entire step/timestep/g" | sed "s/^[ \t ]*//g" | sed "s/  */,/g" | sed "s/,[0-9]\{10\}/,$NUM_CORES,$nicell/g" >>$outfile; }
{ export IBRUN_TASKS_PER_NODE=32 && let NUM_CORES=$IBRUN_TASKS_PER_NODE*$SLURM_NNODES && ibrun $WORKDIR/$EXE --nicell $nicell --outdir $WORKDIR/data | grep "time entire step" | sed "s/time entire step/timestep/g" | sed "s/^[ \t ]*//g" | sed "s/  */,/g" | sed "s/,[0-9]\{10\}/,$NUM_CORES,$nicell/g" >>$outfile; }
{ export IBRUN_TASKS_PER_NODE=16 && let NUM_CORES=$IBRUN_TASKS_PER_NODE*$SLURM_NNODES && ibrun $WORKDIR/$EXE --nicell $nicell --outdir $WORKDIR/data | grep "time entire step" | sed "s/time entire step/timestep/g" | sed "s/^[ \t ]*//g" | sed "s/  */,/g" | sed "s/,[0-9]\{10\}/,$NUM_CORES,$nicell/g" >>$outfile; }
{ export IBRUN_TASKS_PER_NODE=8 && let NUM_CORES=$IBRUN_TASKS_PER_NODE*$SLURM_NNODES && ibrun $WORKDIR/$EXE --nicell $nicell --outdir $WORKDIR/data | grep "time entire step" | sed "s/time entire step/timestep/g" | sed "s/^[ \t ]*//g" | sed "s/  */,/g" | sed "s/,[0-9]\{10\}/,$NUM_CORES,$nicell/g" >>$outfile; }
{ export IBRUN_TASKS_PER_NODE=4 && let NUM_CORES=$IBRUN_TASKS_PER_NODE*$SLURM_NNODES && ibrun $WORKDIR/$EXE --nicell $nicell --outdir $WORKDIR/data | grep "time entire step" | sed "s/time entire step/timestep/g" | sed "s/^[ \t ]*//g" | sed "s/  */,/g" | sed "s/,[0-9]\{10\}/,$NUM_CORES,$nicell/g" >>$outfile; }
{ export IBRUN_TASKS_PER_NODE=2 && let NUM_CORES=$IBRUN_TASKS_PER_NODE*$SLURM_NNODES && ibrun $WORKDIR/$EXE --nicell $nicell --outdir $WORKDIR/data | grep "time entire step" | sed "s/time entire step/timestep/g" | sed "s/^[ \t ]*//g" | sed "s/  */,/g" | sed "s/,[0-9]\{10\}/,$NUM_CORES,$nicell/g" >>$outfile; }
