#!/bin/bash
#SBATCH -J 1-scaling		# Job name
#SBATCH -o 1-scaling-%j.out   # Name of stdout output file (%j expands to jobId)
#SBATCH -e 1-scaling-%j.err   # Name of error output file
#SBATCH -p normal		# Queue name
#SBATCH -N 1                  # Total number of cores requested (64 cores/node, 4 threads/core)
#SBATCH -n 64                 # Total number of mpi tasks requested
#SBATCH -t 2:00:00           # Run time (hh:mm:ss)
#SBATCH --mail-user=nelsonmorrow@utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH -A relplasmas


module load launcher
RAD=250e-9

EXE=psc_test_windowLL
WORKDIR=$SCRATCH/build/src
mkdir $WORKDIR/data

export LAUNCHER_WORKDIR=$HOME/PSC/Scripts
export LAUNCHER_JOB_FILE=scaling
export IBRUN_TASKS_PER_NODE=64
ibrun $WORKDIR/$EXE --nicell 100 --outdir $WORKDIR/data
